### ISSUE TITLE
Do not ignore spaces for chord placement

### ISSUE THREAD

**Issue by RolfSievert** [dnotes/obsidian-markdown-chords#1]
This plugin is really what I need, so thank you for creating it! I just have one feature request to make it perfect.

It would be very nice if spaces weren't ignored when deciding how chords are placed. This might be a behavior of `markdown-it-chords` though.

Currently I have to do this:
```song
[F] . . . [G] . . . [D]
```

but I would like it to work with
```song
[F]       [G]       [D]
```
so that they become more readable.

A more advanced solution would be to make chords not able to overlap, but I can imagine that opens up for all kinds of issues.

**Comment by dnotes** [comment]
Yeah, you're right that this is part of markdown-it-chords; I've made an
issue over there to keep chords from overlapping, which I would love but I
can't think of an easy way to do it.

### Workaround: non-breaking spaces

As a workaround, if you don't like the dots, non-breaking spaces should
work for manually positioning chords. You can type option+space on a Mac. I
don't know what it is for Windows (actually I just looked it up and it's
... alt + 0160? This is begging for a shortcut key!). If nothing else you
can use \&nbsp; or some equivalent HTML entity, which looks horrible in the
code but works fine when it's displayed.

I'll close this issue and leave the one on markdown-it-chords open in case
anyone else has some bright ideas, though I think the non-breaking spaces
will probably work sufficiently well that nobody will spend any development
time on it.

**Comment by dnotes** [comment]
Yeah, you're right that this is part of markdown-it-chords; I've made an issue over there to keep chords from overlapping, which I would love but I can't think of an easy way to do it. 

### Workaround: non-breaking spaces

As a workaround, if you don't like the dots, non-breaking spaces should work for manually positioning chords. You can type option+space on a Mac. I don't know what it is for Windows (actually I just looked it up and it's ... alt + 0160? This is begging for a shortcut key!). If nothing else you can use \&nbsp; or some equivalent HTML entity, which looks horrible in the code but works fine when it's displayed.

I'll close this issue and leave the one on markdown-it-chords open in case anyone else has some bright ideas, though I think the non-breaking spaces will probably work sufficiently well that nobody will spend any development time on it.
