### ISSUE TITLE
Advanced Formatting

### ISSUE THREAD

**Issue by SamGreenwood1** [dnotes/obsidian-markdown-chords#2]
Is there a way to indent lines or have multiple columns? I'm retranscribing an old songbook and want the formatting to be consistent. see an example below:
![image](https://github.com/dnotes/obsidian-markdown-chords/assets/20076209/b62bd521-e580-4132-be3e-78a46d00658d)

**Comment by dnotes** [comment]
You can use the non-breaking space. On Mac you can get a non-breaking space by typing Option+Space, on other systems you might have to use a character finder or just type the HTML entity code as below. It's a bit clunky but it works.

```md
[D] &nbsp; Here comes the sun
```

Feel free to re-open if you feel this needs improvement. Cheers!
